@startuml

title Use Case Diagram

left to right direction

actor Споживач
rectangle "Програма" {
    usecase (Запис даних про сон)
    usecase (Перегляд статистики своїх снів)
    
    Споживач -- (Запис даних про сон)
    Споживач -- (Перегляд статистики своїх снів)
    (Перегляд статистики своїх снів) .> (Запис даних про сон) : include
}

@enduml
