@startuml
title UML-діаграма активності для методу enterSleepData

start

:Споживач обирає опцію "Введення даних про якість сну";

repeat
:Користувач вводить дані про якість сну;
:Виклик методу enterSleepData(sleepData);

if (Дані коректні?) then (Так)
  :Збереження даних про якість сну у системі;
  stop
else (Ні)
  :Виведення повідомлення про помилку;
endif
repeat while (Дані не збережені)
@enduml